import Helmet from "@components/Helmet";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Helmet title="Home">
      <html lang="en">
        <body>
          <main>{children}</main>
        </body>
      </html>
    </Helmet>
  );
}
